name: Build
on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Builder
        shell: bash
        run: |
          export CI_PROJECT_DIR=${PWD}
          export CI_REGISTRY_IMAGE=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}
          export BUILDX_PLATFORM=linux/s390x,linux/386,linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le
          export GO111MODULE=on
          export GO_FLAGS="-tags=netgo"
          export CGO_ENABLED="0"
          export OUTPUT_NAME_WITH_ARCH=false
          echo ${CI_REGISTRY_IMAGE}
          echo ${BUILDX_PLATFORM}
          docker buildx build --platform=${BUILDX_PLATFORM} -f Dockerfile -t ${CI_REGISTRY_IMAGE}/slug-cat:latest --push "."
